pipeline {
    agent any

    parameters {
        string(defaultValue: "",description:"Deployemnt Name?",name:"deploymentName")
        choice(choices:["EU-WEST-2A","EU-WEST-2B","EU-WEST-2C"],description:"What AZ?", name: "azDeployed")
        booleanParam(defaultValue:false,description:"Confirm Deployment?", name:"confirmDeployed")
    }

    stages {
        stage ("Deploy") {
            steps {
                echo "String set to ${deploymentName} \n"
                echo "Choice set to ${azDeployed} \n"
                echo "bool set to: ${params.confirmDeployed} \n"
            }
        }

    }
}