pipeline {
    agent any

    stages{
        stage("Build"){
            steps{
                echo "After the Build this stage will wait for 10 sec then proceed to Test stage"
                sleep(10)
            }
        }

        stage("Test"){
            steps{
                echo "Test completed"
            }
        }
    }
}