pipeline {
    agent any

    environment {
        def cloudName = "AWS"
        def instanceCount = 10
        def multiAz = true
    }

    stages {
        stage("Demo") {
            steps {
                echo "cloudName: ${cloudName}"
                echo "instanceCount: ${instanceCount}"
                echo "multiAZ: ${multiAz}"
            }
        }

    }
}